//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodkart
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AdminMetaData))]
    public partial class Admin
    {
        public long AdminId { get; set; }
        public string AdminUsername { get; set; }
        public string AdminPhone { get; set; }
        public string AdminFName { get; set; }
        public string AdminLName { get; set; }
        public string AdminPassword { get; set; }
        public long AdminMenuId { get; set; }
    
        public virtual Menu Menu { get; set; }
    }

    public partial class AdminMetaData
    {
        public long AdminId { get; set; }

        [Required(ErrorMessage = "Please enter valid username"), RegularExpression(@"^(?=[a-z0-9._]{6,30}$)(?!.*[_.]{2})[^_.].*[^_.]$")]
        public string AdminUsername { get; set; }

        [Required(ErrorMessage = "Please enter valid password"), RegularExpression(@"^[a-zA-Z0-9]{8,20}$")]
        public string AdminPassword { get; set; }

        public string AdminPhone { get; set; }
        public string AdminFName { get; set; }
        public string AdminLName { get; set; }
        public long AdminMenuId { get; set; }

        public virtual Menu Menu { get; set; }
    }
}
