//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodkart
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public long CartItemId { get; set; }
        public long CartItemCartId { get; set; }
        public System.DateTime CartAddDate { get; set; }
        public Nullable<System.DateTime> CartRemoveDate { get; set; }
        public long CartItemQty { get; set; }
        public long CartItemUnitPrice { get; set; }
        public long CartItemFoodId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Food Food { get; set; }
    }
}
